VANILLA_VERSION = optimizations
VANILLA_SITE = $(call github,vanilla-wiiu,vanilla,$(VANILLA_VERSION))
VANILLA_LICENSE = GPL-2.0
VANILLA_LICENSE_FILES = LICENSE
VANILLA_CONF_OPTS = -DVANILLA_BUILD_USE_LIBNM=OFF -DVANILLA_BUILD_USE_POLKIT=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DVANILLA_BUILD_USE_VAAPI=OFF
VANILLA_SUPPORTS_IN_SOURCE_BUILD = NO

$(eval $(cmake-package))
