RTW89_MORROWNR_VERSION = 08b8d326937a200a706ec9c501374eec15835b5a
RTW89_MORROWNR_SITE = $(call github,morrownr,rtw89,$(RTW89_MORROWNR_VERSION))
RTW89_MORROWNR_LICENSE = GPL-2.0 or BSD-3-Clause
RTW89_MORROWNR_LICENSE_FILES = core.c

RTW89_MORROWNR_MODULE_MAKE_OPTS = \
	CONFIG_PCI= \
	RTW89_GIT_COMMIT=$(RTW89_MORROWNR_VERSION)

define RTW89_MORROWNR_INSTALL_USB_STORAGE_CONF
	$(INSTALL) -D -m 0644 $(@D)/usb_storage.conf \
		$(TARGET_DIR)/etc/modprobe.d/rtw89-usb-storage.conf
endef
RTW89_MORROWNR_POST_INSTALL_TARGET_HOOKS += \
	RTW89_MORROWNR_INSTALL_USB_STORAGE_CONF

$(eval $(kernel-module))
$(eval $(generic-package))
