pcm.!default {
    type asym
    playback.pcm {
        type hw
        card tegrasndt210ref
        device 0
    }
    capture.pcm {
        type hw
        card tegrasndt210ref
        device 1          # <-- replace with the DMIC subdevice you found
    }
}

ctl.!default {
    type hw
    card tegrasndt210ref
}
