#include "lang.h"

static const char *lang_str[__VPI_LANG_T_COUNT] = {
    "Sync",
    "Connect",
    "Edit",
    "Settings",
    "OK",
    "Cancel",
    "Touch the symbols in the order they are displayed on the TV screen from left to right.",
    "If the symbols are not displayed on the TV screen, press the SYNC Button on the Wii U console.",
    "Connecting to the Wii U console...",
    "Sync Failed",
    "Vanilla needs root permission to configure the wireless interface for connection.",
    "Please enter your \"sudo\" password here.",
    "Error",
    "No consoles synced",
    "Connecting to \"%s\"...",
    "Are you sure you want to delete \"%s\"?",
    "Successfully deleted \"%s\"",
    "Rename",
    "Delete",
    "Back",
    "More",
    "Controls",
    "Audio",
    "Connection",
    "Webcam",
    "Region",
    "Local",
    "Via Server",
    "Set up how Vanilla connects to the Wii U",
    "Choose 'Local' to connect directly with the hardware on your system. Otherwise, you may need a compatible 'server' to relay the necessary packets.",
    "Select the wireless interface to use for the connection.",
    "Enter the IP address of the server you wish to connect through.",
    "Screenshot saved to \"%s\"",
    "Recording started to \"%s\"",
    "Recording finished",
    "Connection lost, attempting to re-connect...",
    "Your platform is not capable of \"Local\" connection, and must connect via a server.",
    "Failed to save screenshot (%i)",
    "Select gamepad region",
    "Gamepad region must match the console region or else the console will throw an error. This has no other effect on usage.",
    "Japan",
    "America",
    "Europe",
    "Quit",
	"Authentication failed. Please try again.",
	"Don't ask again",
	"WARNING",
	"This option will install a Polkit rule that will allow Vanilla's backend to run as root without password entry.\n\nThere are inherent risks to bypassing security systems. Only enable this if you are willing to accept those risks.\n\nNOTE: If you are using the Steam Deck, this will also disable read-only access to your system partition.",
	"I acknowledge",
	"Enable Root Password Skip",
	"Disable Root Password Skip",
	"Swap AB/XY buttons",
	"Keyboard Controls",
    "Reset To Defaults",
    "Reset",
    "Full Screen",
};

const char *lang(vpi_lang_t id)
{
    return lang_str[id];
}
