#ifndef FRENCH_FR_H
#define FRENCH_FR_H

#include "lang.h"

static const char *lang_str_fr[__VPI_LANG_T_COUNT] = {
    "Synchroniser",
    "Connecte",
    "Modifier",
    "Paramétres",
    "OK",
    "Annuler",
    "Cliquez sur les symboles dans l'ordre affiché dans l'écran TV de gauche à droite.",
    "Si les symboles ne sont pas affichés dans l'écran TV, appuyez sur le bouton SYNC sur la console Wii U.",
    "Connexion à la console Wii U...",
    "Synchronisation échouée",
    "Vanilla a besoin de la permission root pour configurer l'interface sans fils pour la connexion.",
    "Entrez votre \"sudo\" mot de passe ici.",
    "Erreur",
    "Aucune consoles synchronisée",
    "Connexion à \"%s\" en cours...",
    "Êtes-vous sûre que vous voulez supprimer \"%s\"?",
    "\"%s\" Supprimé avec Succès",
    "Renommer",
    "Supprimer",
    "Retour",
    "Plus",
    "Controlles",
    "Audio",
    "Connexion",
    "Caméra",
    "Région",
    "Local",
    "Via Serveur",
    "Mettre en place comment Vanilla se connecte à la Wii U",
    "Choisissez 'Local' pour vous connecter directement avec la matériel sur votre système. Sinon, vous aurez peut-être besoin d'un serveur compatible pour relayer les paquets nécessaires.",
    "Choisissez l'interface sans fil à utiliser pour la connexion.",
    "Entrez l'adresse IP du serveur auquel vous voulez vous connecter",
    "Capture d'écran enregistrée à \"%s\"",
    "L'enregistrement a commencé à \"%s\"",
    "Enregistrement terminé",
    "Connexion perdu, tenter de re-connecter...",
    "Votre plateforme n'est pas capable de \"Local\" connexion, et doit être connectée via un serveur.",
    "Impossible d'enregistrer la capture d'écran (%i)",
    "Choisissez la région du gamepad",
    "La région du gamepad doit être la même que celle de la console ,sinon la console donnera une erreur. Ça n'a pas d'autre effet sur l'usage.",
    "Japan",
    "Amérique",
    "Europe",
    "Quitter",
	"L'authentification a échoué. Veuillez réessayer.",
    "Ne pas demander encore",
	"AVERTISSEMENT",
    "Cette option va installer une règle Polkit qui va permettre au backend de Vanilla d'éxecuter en root sans entrée de mot de passe.\n\nIl n'y a pas de risques inhérents de contourner les systèmes de sécurité. Activez cette option si vous acceptez cez risques.\n\nNOTE: Si vous utilisez le Steam Deck, ça va aussi déactiver read-only access de votre partition système.",
    "Je comprend",
    "Activer le Skip de Mot de Passe Root",
    "Désactiver le Skip du Mot de Passe Root",
    "Inverser les boutons AB/XY",
    "Plein Écran",
};

#endif
