#ifndef VANILLA_PIPE_H
#define VANILLA_PIPE_H

// Control codes that our pipe will receive
enum PipeOpCodes
{
    VANILLA_PIPE_IN_SYNC = 1,
    VANILLA_PIPE_IN_CONNECT,
    VANILLA_PIPE_IN_BUTTON,
    VANILLA_PIPE_IN_TOUCH,
    VANILLA_PIPE_IN_REQ_IDR,
    VANILLA_PIPE_IN_REGION,
    VANILLA_PIPE_IN_BATTERY,

    VANILLA_PIPE_IN_INTERRUPT = 0x1E,
    VANILLA_PIPE_IN_QUIT = 0x1F,

    VANILLA_PIPE_OUT_DATA = 0x20,
    VANILLA_PIPE_OUT_SYNC_STATE,
    VANILLA_PIPE_OUT_EOF,

    // Errors that our pipe will send
    VANILLA_PIPE_ERR_SUCCESS = 0x30,
    VANILLA_PIPE_ERR_UNK,
    VANILLA_PIPE_ERR_INVALID,
    VANILLA_PIPE_ERR_BUSY
};

#endif // VANILLA_PIPE_H