name: Build
on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            arch: x86_64
            artifact: vanilla-linux-x86_64.tar.gz
          - os: linux
            arch: aarch64
            artifact: vanilla-linux-aarch64.tar.gz
          - os: windows
            arch: x86_64
            artifact: vanilla-windows-x86_64.zip
          - os: android
            arch: universal
            artifact: vanilla-android-universal.apk
          - os: macos
            arch: universal
            artifact: vanilla-macos-universal.zip
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies for cross-compiling
      if: ${{ matrix.platform.arch != 'x86_64' && matrix.platform.os == 'linux' }}
      run: sudo apt -y update && sudo apt -y install qemu-user-static binfmt-support

    - uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: docker/${{ matrix.platform.os }}
        build-args: |
            ARCH=${{ matrix.platform.arch }}
        tags: vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
        load: true
        cache-from: type=gha,scope=vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
        cache-to: type=gha,scope=vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }},mode=max

    - name: Run Docker container
      run: |
        docker run \
            -v "${{ github.workspace }}:/vanilla" \
            -v "${{ github.workspace }}/build:/install" \
            -e ANDROID_SIGNING_KEY=${{ secrets.ANDROID_SIGNING_KEY }} \
            vanilla-${{ matrix.platform.os }}-${{ matrix.platform.arch }}

    - name: Archive (Linux)
      if: ${{ matrix.platform.os == 'linux' }}
      run: |
        tar czf ${{ matrix.platform.artifact }} -C "${{ github.workspace }}/build" .

    - name: Archive (Windows/macOS/Raspberry Pi/Nintendo Switch)
      if: ${{ matrix.platform.os == 'windows' || matrix.platform.os == 'macos' || matrix.platform.os == 'raspberrypi0w' || matrix.platform.os == 'raspberrypizero2w' || matrix.platform.os == 'nintendoswitch' }}
      run: |
        cd build
        zip -r ../${{ matrix.platform.artifact }} .

    - name: Archive (Android)
      if: ${{ matrix.platform.os == 'android' }}
      run: |
        cp build/app-release.apk ${{ matrix.platform.artifact }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform.os }} ${{ matrix.platform.arch }}
        path: ${{ matrix.platform.artifact }}

    - name: Upload Continuous Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'vanilla-wiiu/vanilla' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -fLOSs --retry 2 --retry-delay 60 https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh ${{ matrix.platform.artifact }}
  buildroot:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: raspberrypi0w
            arch: armv6l
            artifact: vanilla-raspberrypi0w-image.zip
          - os: raspberrypizero2w_64
            arch: aarch64
            artifact: vanilla-raspberrypizero2w_64-image.zip
          - os: nintendoswitch
            arch: aarch64
            artifact: vanilla-nintendoswitch-image.zip
    runs-on: ubuntu-24.04
    env:
      BUILDROOT_PATH: ${{ github.workspace }}/../buildroot
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies for Buildroot
      if: ${{ matrix.platform.arch != 'x86_64' && matrix.platform.os == 'linux' }}
      run: |
        apt -y update
        apt -y install which \
          sed \
          make \
          binutils \
          build-essential \
          diffutils \
          gcc \
          g++ \
          bash \
          patch \
          gzip \
          bzip2 \
          perl \
          tar \
          cpio \
          unzip \
          rsync \
          file \
          bc \
          findutils \
          gawk \
          wget \
          git

    - name: Cache Buildroot
      id: cache-buildroot
      uses: actions/cache@v4
      with:
        path: vanilla-buildroot-cache
        key: ${{ matrix.platform.os }}-buildroot-system

    - name: Acquire Buildroot
      if: steps.cache-buildroot.outputs.cache-hit != 'true'
      run: git clone --depth 1 --branch 2025.11-rc2 https://github.com/buildroot/buildroot.git $BUILDROOT_PATH

    - name: Build Vanilla
      run: |
        # Use the copy of Vanilla provided by us rather than downloading
        make -C $BUILDROOT_PATH BR2_EXTERNAL="$GITHUB_WORKSPACE"/buildroot vanilla_${{ matrix.platform.os }}_defconfig
        $BUILDROOT_PATH/utils/config -e BR2_PACKAGE_VANILLA_USE_LOCAL
        $BUILDROOT_PATH/utils/config --set-str BR2_PACKAGE_VANILLA_LOCAL_PATH "$GITHUB_WORKSPACE"

        # Build, ensuring Vanilla is rebuilt from scratch (since old versions may have been left in the cache)
        make -C $BUILDROOT_PATH vanilla-dirclean
        make -C $BUILDROOT_PATH

    - name: Archive (Raspberry Pi)
      if: matrix.platform.os == 'raspberrypi0w' || matrix.platform.os == 'raspberrypizero2w'
      run: |
        zip $GITHUB_WORKSPACE/${{ matrix.platform.artifact }} $BUILDROOT_PATH/output/images/sdcard.img

    - name: Archive (Nintendo Switch)
      if: matrix.platform.os == 'nintendoswitch'
      run: |
        zip $GITHUB_WORKSPACE/${{ matrix.platform.artifact }} $BUILDROOT_PATH/output/images/rootfs.cpio.gz

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform.os }} ${{ matrix.platform.arch }}
        path: ${{ matrix.platform.artifact }}

    - name: Upload Continuous Release
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'vanilla-wiiu/vanilla' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -fLOSs --retry 2 --retry-delay 60 https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh ${{ matrix.platform.artifact }}

